### ISSUE TITLE
Error occurred when i try to create snippet in .yml file

### ISSUE THREAD

**Issue by iamDvz** [Abhishekkumar2021/code-to-snippet#1]
I try to do a snippet for 
```
dummy:
    spell-class: ".instant.DummySpell"
    helper-spell: true
```
But i have error

**Comment by Abhishekkumar2021** [comment]
Thank you for pointing it out. I have resolved that issue and now the extension is working fine.

https://github.com/Abhishekkumar2021/code-to-snippet/assets/83966143/72d21dc6-9306-4733-a921-ad635b7220c1

Thanks again.
